#!/usr/bin/env php
<?php


if ($_SERVER['REMOTE_ADDR'] == '127.0.0.1') {
   // defined('YII_DEBUG') or define('YII_DEBUG', true);
} else {
   // defined('YII_DEBUG') or define('YII_DEBUG', false);
}


// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/console/config/console.php');

$application = new panix\engine\console\Application($config);
//$application = new \yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
